@token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJlZGl2YWxkb0BlbWFpbC5jb20iLCJpYXQiOjE3OTAxMTk2NjQsImV4cCI6MTc5MDEyMzI2NH0.6ATLIKmczoUFTD1q02NTtGzOzbs7_4TOipkUZulZhd8"

### CADASTRAR USUÁRIO
POST http://localhost:3000/usuarios
Content-Type: application/json

{
  "nome": "Richard Bassetto",
  "email": "richard@gmail.com",
  "senha": "123456"
}

### LOGIN
POST http://localhost:3000/usuarios/login
Content-Type: application/json

{
  "email": "edivaldo@email.com",
  "senha": "123456"
}

### PERFIL
GET http://localhost:3000/usuarios/perfil
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJlZGl2YWxkb0BlbWFpbC5jb20iLCJpYXQiOjE3OTAyOTUzMDIsImV4cCI6MTc5MDI5ODkwMn0.uq0q2HC8fiP4nBNU6iMRl13taOTzrzs-fBInSvBuGPU

### PERFIL SEM TOKEN
GET http://localhost:3000/usuarios/perfil

### PERFIL COM TOKEN
GET http://localhost:3000/usuarios/perfil
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJlZGl2YWxkb0BlbWFpbC5jb20iLCJpYXQiOjE3OTAyMDQwNzQsImV4cCI6MTc5MDIwNzY3NH0.jBzIJm-_GfYVwAxNE8wOZHBcc7QWttAzBxqGVU67JOs

### CRIAR TAREFA
POST http://localhost:3000/tarefas
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJlZGl2YWxkb0BlbWFpbC5jb20iLCJpYXQiOjE3OTAyMDQwNzQsImV4cCI6MTc5MDIwNzY3NH0.jBzIJm-_GfYVwAxNE8wOZHBcc7QWttAzBxqGVU67JOs

{
  "titulo": "Estudar alguma coisa",
  "descricao": "Continuar projeto Task Manager",
  "status": "pendente",
  "prazo": "2026-09-25"
}

### LISTAR TAREFAS
GET http://localhost:3000/tarefas
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJlZGl2YWxkb0BlbWFpbC5jb20iLCJpYXQiOjE3OTAyOTUzMDIsImV4cCI6MTc5MDI5ODkwMn0.uq0q2HC8fiP4nBNU6iMRl13taOTzrzs-fBInSvBuGPU

### ATUALIZAR TAREFA
PUT http://localhost:3000/tarefas/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJlZGl2YWxkb0BlbWFpbC5jb20iLCJpYXQiOjE3OTAyMDQwNzQsImV4cCI6MTc5MDIwNzY3NH0.jBzIJm-_GfYVwAxNE8wOZHBcc7QWttAzBxqGVU67JOs

{
  "titulo": "Estudar React 2",
  "descricao": "Apos montar o backend, trabalhar no frontend",
  "status": "pendente",
  "prazo": "2026-09-30"
}

### EXCLUIR TAREFA
DELETE http://localhost:3000/tarefas/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJlZGl2YWxkb0BlbWFpbC5jb20iLCJpYXQiOjE3OTAxMjMzNzAsImV4cCI6MTc5MDEyNjk3MH0.uwf6Yn2_dw_oVhgyesBhnGj1-zAqjXeZnhtVTRqstEI