@token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJlZGl2YWxkb0BlbWFpbC5jb20iLCJpYXQiOjE3OTAxMTk2NjQsImV4cCI6MTc5MDEyMzI2NH0.6ATLIKmczoUFTD1q02NTtGzOzbs7_4TOipkUZulZhd8"

### CADASTRAR USUÁRIO
POST http://localhost:3000/usuarios
Content-Type: application/json

{
  "nome": "Edivaldo",
  "email": "edivaldo@email.com",
  "senha": "123456"
}

### LOGIN
POST http://localhost:3000/usuarios/login
Content-Type: application/json

{
  "email": "edivaldo@email.com",
  "senha": "123456"
}

### PERFIL SEM TOKEN
GET http://localhost:3000/usuarios/perfil

### PERFIL COM TOKEN
GET http://localhost:3000/usuarios/perfil
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJlZGl2YWxkb0BlbWFpbC5jb20iLCJpYXQiOjE3ODk3NzM3NzMsImV4cCI6MTc4OTc3NzM3M30.kN7-mbqIMqClV4XtbUJqCIdpynJJY6MEhJ-YhgKBdH0

### CRIAR TAREFA
POST http://localhost:3000/tarefas
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJlZGl2YWxkb0BlbWFpbC5jb20iLCJpYXQiOjE3ODk3NzM3NzMsImV4cCI6MTc4OTc3NzM3M30.kN7-mbqIMqClV4XtbUJqCIdpynJJY6MEhJ-YhgKBdH0

{
  "titulo": "Estudar Node",
  "descricao": "Continuar projeto Task Manager",
  "status": "pendente",
  "prazo": "2026-09-25"
}

### LISTAR TAREFAS
GET http://localhost:3000/tarefas
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJlZGl2YWxkb0BlbWFpbC5jb20iLCJpYXQiOjE3OTAxMjMzNzAsImV4cCI6MTc5MDEyNjk3MH0.uwf6Yn2_dw_oVhgyesBhnGj1-zAqjXeZnhtVTRqstEI

### ATUALIZAR TAREFA
PUT http://localhost:3000/tarefas/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJlZGl2YWxkb0BlbWFpbC5jb20iLCJpYXQiOjE3OTAxMTk2NjQsImV4cCI6MTc5MDEyMzI2NH0.6ATLIKmczoUFTD1q02NTtGzOzbs7_4TOipkUZulZhd8

{
  "titulo": "Estudar React 2",
  "descricao": "Apos montar o backend, trabalhar no frontend",
  "status": "pendente",
  "prazo": "2026-09-30"
}

### EXCLUIR TAREFA
DELETE http://localhost:3000/tarefas/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJlZGl2YWxkb0BlbWFpbC5jb20iLCJpYXQiOjE3OTAxMjMzNzAsImV4cCI6MTc5MDEyNjk3MH0.uwf6Yn2_dw_oVhgyesBhnGj1-zAqjXeZnhtVTRqstEI